# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    exception:
      exception_controller: 'fos_rest.exception.controller:showAction'
    body_converter:
      enabled: true
      validate: true
      validation_errors_argument: validationErrors
    format_listener:
      rules:
        - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
